### ISSUE TITLE
Index h3s in docs for search

### ISSUE THREAD

**Issue by kimberleyamackenzie** [pulumi/docs#10123]
I was searching for a specific piece of info about deployments, and I searched the term "dependency installation" in docs. 
 My search returned 0 results, and I had to ask someone on the project for details, and they linked me to this page -  https://www.pulumi.com/docs/pulumi-cloud/deployments/reference/#customizing-the-dependency-installation-step.  I was surprised that I didn't find that via search, given the phrase appears in the h3 there.

**Comment by thoward** [comment]
This is a good call out. According to the script that builds the index, we've explicitly chosen *not* to include H3s because they are "too noisy": https://github.com/pulumi/docs/blob/master/scripts/search/page.js#L54 ... 

A decision should be made here. Should we include all H3s as well as H2s? (it's a simple change to the jQuery selector in that same location) Or accept that we won't include them and close this as `wont-fix`/`by-design`? 

@interurban @sean1588

**Comment by thoward** [comment]
After some discussion, going to reopen and fix this.
