### ISSUE TITLE
Update Lifting page content

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#10559]
Mar 8: There doesn't really seem to be a clear cut way to explain the times when Lifting doesn't work and why. Will default to "if Lifting doesn't work, then try with apply instead". Also need to enhance the examples.

Include content around Typing and its importance in knowing when you can and cant access certain nested values/objects.

It's important to understand the way Typing works in Pulumi:

`vpc` is `pulumi.Output['pulumi_aws.ec2.Vpc']` - a resource
`vpc.vpc` is an `Output[Resource]` - a property that is a resource object
`vpc.vpc.arn` is an `Output[string]` - a property that is a string
`vpc.private_subnets_id` is `Output[Sequence[str]]` - a property that is a list of strings
 `Mapping[str, str]` - a property that is a Dict

These Types are represented very differently across languages.

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/docs/issues/10798
- [ ] https://github.com/pulumi/docs/issues/10799
```

**Comment by toriancrane** [comment]
In the [Accessing Nested Properties of an Output by Lifting](https://www.pulumi.com/docs/concepts/inputs-outputs/#lifting) section, there are the following code snippets:

```
let certCertificate = new aws.acm.Certificate("cert", {
    domainName: "example.com",
    validationMethod: "DNS",
});

// Apply example which would be replaced by the lifting example
let certValidation = new aws.route53.Record("cert_validation", {
    records: [
        // Need to pass along a deep subproperty of this Output
        certCertificate.domainValidationOptions.apply(
            domainValidationOptions => domainValidationOptions[0].resourceRecordValue),
    ],
    ...
});

// Lifting example
let certValidation = new aws.route53.Record("cert_validation", {
    records: [
        certCertificate.domainValidationOptions[0].resourceRecordValue
    ],
...


// Chaining example which would be replaced by the exact same lifting example

let certValidation = new aws.route53.Record("cert_validation", {
  records: [certCertificate.apply(cc => cc ? cc.domainValidationOptions : undefined)
                           .apply(dvo => dvo ? dvo[0] : undefined)
                           .apply(o => o ? o.resourceRecordValue : undefined)],

```

Can someone re-explain what is happening here to someone not deeply familiar with the workings of TypeScript? I am especially confused about how the lifting example translates to both the apply example and the chaining example. The chaining example looks like it is doing a bunch of extra stuff.

**Comment by cnunciato** [comment]
The `.apply().apply()` example is just wrong: `certCertificate.apply()` isn't a thing, because `certCertificate` isn't an output, it's a `Certificate`:

```
Property 'apply' does not exist on type 'Certificate'.
```

Even if this did work, though, `records: [ undefined ]` wouldn't work anyway, because `records` is typed as `Input<string>`, not `Input<string | undefined>`. 

We should simply this. It doesn't help and it's not even clear to me what it's trying to explain, other than that "you can chain calls to `apply`". That you can do this is good to know, so it'd be good to explain it somewhere, but it needn't be tied to the concept of lifting.

As for why lifting works, [this line](https://github.com/pulumi/pulumi/blob/bd93fcf91a11b227adfdc8bd9904ea4d46e4485b/sdk/nodejs/output.ts#L956) explains at least the typing of it:

```typescript
export type Output<T> = OutputInstance<T> & Lifted<T>;
```

That means that (in Node.js at least) an `Output<T>` is either a normal output of the given type (requiring the use of `apply()`) or an instance of that same type (although that isn't _actually_ true -- it's just that the [`apply` has been called for you](https://github.com/pulumi/pulumi/blob/bd93fcf91a11b227adfdc8bd9904ea4d46e4485b/sdk/nodejs/output.ts#L282)).  This explains why the following two accessors work:

```typescript
const foo = pulumi.output([ { prop: "value" }]);

foo.apply(f => f[0].prop); // as an OutputInstance<T>
foo[0].prop;               // as a Lifted<T>
```

As to whether we should remove the documentation of it, I'm not sure. I do like the idea of leaning into `apply()` as the One True Way, for sure. The trouble however is that lifting _exists_, so people are going to wonder what it is when they see it. So my suggestion would probably be to cover it, but be clear that it's essentially syntactic sugar for `apply()` and that it only works only in Node.js. (I believe my assumptions are correct on this, but we should confirm just in case.)
