### ISSUE TITLE
YouTube Short Code does not preview at timestamp

### ISSUE THREAD

**Issue by jkodroff** [pulumi/docs#11600]
### What happened?

When displaying a YouTube shortcode, the timestamp is not respected. Example:

This link (which comes from the "share" button on the YT site):

```
https://www.youtube.com/live/-siv1ga0l_o?feature=share&t=12576
```

Translated into this shortcode:

```
{{< youtube "-siv1ga0l_o?t=12576&rel=0" >}}
```

Displays the video at 0:00:00, not 3:31:46.

### Expected Behavior

n/a

### Steps to reproduce

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thoward** [comment]
Fixed in PR https://github.com/pulumi/docs/pull/13476 . This issue will close when that merges. See description there for context. Basically, old Hugo didn't support timestamps on YouTube video embeds, but new Hugo does, however it doesn't support YouTube embeddings inside of notes, so I fixed both.
