### ISSUE TITLE
blog list page kinda broken with many authors

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#11677]
this looks kinda broken on the blog list page with more than a couple authors
we may want to to figure out a design pattern here that supports more than a couple authors
this many authors do work on the blog page itself
![blog-list](https://user-images.githubusercontent.com/5489125/168970191-701292f2-1157-47c3-badd-16fa98a68174.png)

**Comment by thoward** [comment]
This is a great idea (and still an issue with our current design), however since we have had no motion on this in 2.5 years, and the ticket isn't written in a way that is immediately actionable, I'm going to close this as `wont-fix` for now. We can reopen if we start addressing blog theme/layout issues.
