### ISSUE TITLE
Bottom 20% of the nav is not clickable

### ISSUE THREAD

**Issue by jkodroff** [pulumi/docs#12072]
In the browser, all the links in the following picture from "Environments (ESC)" and below are not clickable links.

<img width="248" alt="image" src="https://github.com/pulumi/docs/assets/410614/4ae5cf40-4c6e-4753-909b-d9ce8f7516ef">

The bug occurs for me in Safari and Chrome, but not Firefox. I've verified that it's related to the position of the elements on the screen, not the content. In other words, if I scroll, the bottom 20% or so of the links are unclickable no matter what the link is.

**Comment by cnunciato** [comment]
@jkodroff Does this repro reliably on a hard page reload? Is it possible there's a cookie banner open at the bottom of the page? (I haven't been able to repro yet.)

**Comment by cnunciato** [comment]
Ok yeah, I suspect what you're seeing is because of the cookie banner that shows up in the lower-left corner. The outlined area here is not clickable because the banner's container is blocking it:

![Image](https://github.com/pulumi/docs/assets/274700/82250580-3965-4f97-9059-c7b77f9023c5)

Does closing the banner fix the issue?

**Comment by jkodroff** [comment]
I don't see the cookie banner. In this screenshot, everything from "Pulumi Cloud" to the bottom of the screen is unclickable, but only in the nav. The links at the bottom of the main content work fine:

<img width="1674" alt="image" src="https://github.com/pulumi/docs/assets/410614/6dbfc168-bcc6-4b94-ba59-f38b9a53ca93">
