### ISSUE TITLE
Travis jobs are slow

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#1302]
Builds times are all over the place - from 5mins to >30mins.

https://travis-ci.com/pulumi/docs/builds

And watching the build run just now, it was just sluggishly updating a singe BucketObject at a time.  These should be parallelized.  

Given current workflow, this means ~1.5hr from content to production (PR into master, merge into master, PR into prod, merge into prod - the 1st, 3rd and 4th of which by the letter of the law should be serialized).

**Comment by chrsmith** [comment]
Some notes:

- We should be running multiple jobs concurrently in Travis. We can only safely do so for `push` jobs which update a stack by running our `travisqueue` tool. (Enabled [here](https://github.com/pulumi/docs/blob/master/.travis.yml#L13).
- When standing up the stacks I capped the parallelism at 10. (See [run-pulumi.sh](https://github.com/pulumi/docs/blob/master/scripts/run-pulumi.sh#L32).) This was because my machine became ~unusable when `pulumi` tried to update/refresh 3,000+ resources at the same time. We can probably up that to some reasonable amount, but I suspect unbounded parallelism would lead to system resource problems on the CI machine. (Similar to networking woes before we were batching engine events.)

**Comment by lukehoban** [comment]
> When standing up the stacks I capped the parallelism at 10. (See run-pulumi.sh.) This was because my machine became ~unusable when pulumi tried to update/refresh 3,000+ resources at the same time. We can probably up that to some reasonable amount, but I suspect unbounded parallelism would lead to system resource problems on the CI machine. (Similar to networking woes before we were batching engine events.)

Ahh - yes - that is going to be the culprit here.  I'm honestly surprised that even at unbounded parallelism this led to any issues.  I'll try out increasing the parallelism.

**Comment by justinvp** [comment]
One thing I've noticed that adds to build times is the broken link checker. Need to see if there's a way to speed that up, or just not run it all the time (daily cron job only?).

**Comment by stack72** [comment]
Closing out as we are no longer on travis :)
