### ISSUE TITLE
Randomize team members on the About page

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#1330]

**Comment by chrsmith** [comment]
This used to be the case because every team member was given the same weight of 1, and so we were dependent upon the random ordering that you would iterate through the map in Hugo. Not sure what change was made to prevent that, but the result was that the team listing would be randomized every time the site was rendered.

**Comment by joeduffy** [comment]
We had custom JavaScript in the old service to implement this -- it wasn't purely due to the weight of 1. Note that the order of VCs is also wrong on the page, let's fix this while we're in there too (Soma, Sheila, Maria, Stacey).

**Comment by mikhailshilkov** [comment]
If you are fine with randomizing at the time of generation, then it's a matter of adding `| shuffle` after `range $.Site.Data.team.team`. That will shuffle the order in HTML, so every visitor will see the same order until the next version of the site is deployed.

**Comment by cnunciato** [comment]
#1334 should fix this with a little JS, but I'm also personally okay with randomizing at build time, too, if anyone prefers that approach.
