### ISSUE TITLE
Add body of blog post to RSS feed.

### ISSUE THREAD

**Issue by aydrian** [pulumi/docs#1349]
The current RSS Feed doesn't offer more than the description. It would be nice to have the body of the post included.

**Comment by chrsmith** [comment]
@cnunciato what do you think about doing this?

Evidently [this](https://cyber.harvard.edu/rss/rss.html) is the official spec for RSS, and it doesn't look like there is a specific `<content>` element. I guess the convention is to just put the full post's contents in the `<description>` element?

I'm all for having full posts in the RSS feed, since that is much more useful, but I worry that we might run afoul of character escaping or something since the content could contain invalid XML characters. Perhaps just adding `{{ .Content | xml-safe }}` or something is all that's needed to put in `layouts/blog/rss.xml`?

**Comment by cnunciato** [comment]
I’m in favor of this too, yeah. Thanks for bringing it up.
