### ISSUE TITLE
Fix first batch of mobility issues on website

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#1401]
The Google Search Console for www.pulumi.com is reporting a lot of "mobility issues" for pages. I suspect that all of these are duplicates of a small class of core issues in our layouts and/or CSS.

Mobility Usage dashboard
https://search.google.com/u/1/search-console/mobile-usability?resource_id=sc-domain%3Apulumi.com&hl=en

I don't think we want to spend the time to fix 100% of these issues in the current milestone. But if we time-boxed it to ~5-10 targeted fixes, I would guess we can remove a lot of these problems.

Now as far as the core dev/test loop, do _not_ visit https://search.google.com/test/mobile-friendly. As that seems to report fewer items than the more in-depth Google Search Console. Instead, use the page here, and click "TEST LIVE URL":

https://search.google.com/u/1/search-console/inspect/mobile-usability?resource_id=sc-domain%3Apulumi.com&id=DIp3ZwAMy200QN_SIq3vPQ&hl=en

That will point out:

- Content is wider than screen
- Clickable elements too close together

Unfortunately for both of those, it doesn't tell us exactly what element(s) on the page are the offenders. But it is close enough to get started on some sort of investigation.

Part of https://github.com/pulumi/home/issues/514

**Comment by cnunciato** [comment]
#1426 fixed all `Content wider than screen` errors.

**Comment by cnunciato** [comment]
Looks like `Clickable elements too close together`'s all good now, too.

**Comment by cnunciato** [comment]
... and `Text too small to read` looks green now, too. 

The Mobile-Friendly overview doesn't seem to have updated yet, but individually clicked URLs are all green, with two exceptions:

* `https://www-production.pulumi.com/docs/quickstart/aws/modify-program/`, which is presumably happening because the page has been indexed -- we've since set a `canonical` URL, so it shouldn't affect SEO negatively, but since it's the result of a `production` build, `Disallow: *` isn't applied -- but the page fails the CSS integrity check. If we can somehow block this host from responding at all, that'd be best, but I'm not concerned about this page's mobile friendliness.

* `https://www.pulumi.com/blog/page/3/`. For some reason, Google's test UI is reporting issues with this page that have been fixed with all other pages, but the page is clearly okay, so I'm comfortable ignoring this for now.

Closing as fixed by #1426.

**Comment by chrsmith** [comment]
> but the page fails the CSS integrity check. If we can somehow block this host from responding at all, that'd be best.

The `www-production` DNS record was created as part of the devstack. So it seems like we might want to just update the underlying Pulumi program to no longer create that record... I'd need to think about it a little more.

> https://www.pulumi.com/blog/page/3/. For some reason, Google's test UI is reporting issues with this page that have been fixed with all other pages

I would guess it has to do with a particular blog post on that page, right? e.g. whatever markup is in its particular summary blurb? If we ignore it for now, I just wonder if it will come back as `/page/4` and `/page/5`, etc.

**Comment by cnunciato** [comment]
> I would guess it has to do with a particular blog post on that page, right?

I'd guess the same thing, so 🤷‍♂. Could definitely spend more time getting to the bottom of why the bot isn't happy with something about this page, but as a human looking at it on a real device, and in desktop emulators, I'm not seeing any issues, so I'm okay with it for now.
