### ISSUE TITLE
Formatting changes halfway through page

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1429]
Something is causing the font style to change halfway down this API Reference page. Text is going from "normal" to "bold" for some reason.

https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/s3/#Inventory-bucket

![image](https://user-images.githubusercontent.com/293763/61667864-fe676300-ac8f-11e9-943e-cd038ee6b975.png)

**Comment by chrsmith** [comment]
Perhaps there is a lonely `<b>` tag missing its partner 🙃 .

**Comment by justinvp** [comment]
Buckle up, here's what's going on:

1. `sseS3` is [typed](https://github.com/pulumi/pulumi-aws/blob/a4e17c3cf20eda684061d667ba19db82920d6ca3/sdk/nodejs/s3/inventory.ts#L98) as an empty type literal:

   ```typescript
   sseS3?: {  }
   ```

1. [typedoc uses `__type` as the type name for type literals](https://github.com/TypeStrong/typedoc/blob/e9b28ee2c336617687a968820515b6a37d44515f/src/lib/converter/types/reference.ts#L127-L128)

1. We emit typedoc type names:

   https://github.com/pulumi/docs/blob/bacc6cbd4695bdcbaeaf24cf713c9948e8c69cd7/tools/tscdocgen/main.go#L986

1. So we end up emitting a type named `__type` in the generated [`pkg/nodejs/pulumi/aws/s3/_index.md`](https://github.com/pulumi/docs/blob/bacc6cbd4695bdcbaeaf24cf713c9948e8c69cd7/content/docs/reference/pkg/nodejs/pulumi/aws/s3/_index.md#L2035) file:

   ```typescript
   sseS3: undefined | __type;
   ```

1. Hugo's markdown rendered sees `__` (double underscores) and renders a `<strong>`, but there is no closing `__`, so there is an open `<strong>` with no closing `</strong>`.

We could workaround the markdown issue by prefixing `__type` as `\__type`, to prevent the open `<strong>` from being rendered. But that just works around the markdown rendering issue. The real fix would be to render the type literal instead of the name, e.g. `{ }` instead of `__type`. Need to investigate more to see how doable that is.
