### ISSUE TITLE
Nested types (inputs and outputs) aren't shown and aren't linked in API docs

### ISSUE THREAD

**Issue by lblackstone** [pulumi/docs#1467]
### Problem description

- I saw a product documentation issue on the following URL: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kubernetes/

None of the input/output types are linked in the k8s Node API reference docs.
For example, https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kubernetes/apps/v1/#Deployment-constructor shows  that `args` is of the `inputApi.apps.v1.Deployment` type, but that type is not linked.

### Suggestions for a fix

The Node SDK in the k8s provider may need to be updated to reference the exported types for the doc generator to work properly.

**Comment by justinvp** [comment]
I took a brief look at this since I'm working on a change to emit nested structures as named types in the TF providers (https://github.com/pulumi/pulumi-terraform/issues/317), and am doing it in a similar way as the K8s provider: emitting these input/output types in their own `types` module.

The first thing I did was deleted the following lines:

https://github.com/pulumi/docs/blob/c47cf231cef41b2c15b96754b743c4ac6560f79f/tools/tscdocgen/main.go#L524-L528

After that, I didn't get very far.

Running `PKGS=kubernetes ./scripts/run_typedoc.sh`

```
Generating pulumi.com API docs
go run ./tools/tscdocgen/main.go ./tools/tscdocgen/template.go ../pulumi-kubernetes/sdk/nodejs /var/folders/4q/8cmjgthn18x9gwgq4fvf4q7w0000gn/T/tmp.VBBdEgAD/kubernetes.docs.json ./content/docs/reference/pkg/nodejs/pulumi/kubernetes a33c437ad5b9a9ea70aee20e57d219eb55b3f11b
error: emitting Markdown docs: cannot merge two nodes with same name 'admissionregistration'; incompatible types Module and Module
exit status 2
```

This error is coming from: https://github.com/pulumi/docs/blob/c47cf231cef41b2c15b96754b743c4ac6560f79f/tools/tscdocgen/main.go#L746-L777

Need to look more into `Merge`.

**Comment by justinvp** [comment]
Even if we address/workaround the issue in `Merge`, we'll likely still have an issue with the namespaces not showing up in the generated docs. This is tracked in https://github.com/pulumi/docs/issues/1518.
