### ISSUE TITLE
Broken link for "Python Getting Started" 

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1559]
File: [docs/reference/pkg/python/pulumi/_index.md](https://www.pulumi.com/docs/reference/pkg/python/pulumi/)

Link points to https://www.pulumi.com/reference/python.html#getting-started 

@justinvp Did this page get moved?

**Comment by justinvp** [comment]
The problem is here:

https://github.com/pulumi/docs/blob/48e32082eba0468cdff5d6255e608b64313e5f8e/tools/pydocgen/pydocgen/templates/providers/pulumi.rst#L12-L13

This used to be the URL before the site migration, and if you try to navigate to https://pulumi.io/reference/python.html#getting-started, it will redirect correctly. But as specified as `/reference/python.html#getting-started`, the browser will try to navigate to https://www.pulumi.com/reference/python.html#getting-started, which doesn't exist.

We didn't catch this because we exclude the API docs from the broken link checker due to the number of broken links from the TF providers. It may be worth going through and making the exclusions more granular so we more easily find these broken links.

I'll take care of fixing this particular issue.
