### ISSUE TITLE
Add more tutorials

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1577]
We have 5 AWS tutorials, 10 Kubernetes tutorials, and 1 each for Azure and GCP. That feels a bit uneven to me. We can probably just take some of our excellent examples and blogs and turn them into tutorials without much effort (I still wish there was a way for us to write one guide and have it emit the example and tutorial, so that it's easy to keep closer to parity here).

**Comment by mikhailshilkov** [comment]
Great idea! Here are some options for Azure.

### App Service (choose one)

- ASP.NET app + SQL Server, based on [this example](https://github.com/pulumi/examples/tree/master/azure-ts-appservice) and [this blog](https://www.pulumi.com/blog/level-up-your-azure-platform-as-a-service-applications-with-pulumi/), might be a bit involved due to the custom code
- Docker, based on [this example](https://github.com/pulumi/examples/tree/master/azure-ts-appservice-docker) or [that example](https://github.com/pulumi/examples/tree/master/azure-ts-appservice-springboot), simple but yet another dummy web server
- Node app + Cosmos DB, no example yet, but might make sense in light of our focus on Cosmos

### Functions (choose one)

- Deploying an "external" function, based on [this example](https://github.com/pulumi/examples/tree/master/azure-ts-functions-raw)
- Function as callback, based on [this example](https://github.com/pulumi/examples/tree/master/azure-ts-functions) and [this blog](https://www.pulumi.com/blog/serverless-as-simple-callbacks-with-pulumi-and-azure-functions/)
- URL shortener, based on [this example](https://github.com/pulumi/examples/tree/master/azure-ts-serverless-url-shortener-global) and [this blog](https://mikhail.io/2019/07/globally-distributed-serverless-application-in-100-lines-of-code/)
- Some other end-to-end application, e.g. [Todo-Backend](https://www.todobackend.com/) implemented with Functions and Cosmos/Redis

### VMs (choose one)

- Web server, based on [this example](https://github.com/pulumi/examples/tree/master/azure-ts-webserver] or [that example](https://github.com/pulumi/examples/tree/master/azure-ts-webserver-component)
- Web server on VM Scale Sets, based on [this example](https://github.com/pulumi/examples/tree/master/azure-ts-vm-scaleset)

### AKS

Less of priority because it's already mentioned in the Kubernetes tutorials

### Static website

- Hosting a static website, based on [this example](https://github.com/pulumi/examples/tree/master/azure-ts-static-website) and [this blog](https://mikhail.io/2019/06/hosting-a-static-website-on-azure-with-pulumi/), might be too involved

### Messaging and integrations

- A bot posting Stack Overflow questions to Slack, Aydrian made one? where is it?
- Event Hubs + Stream Analytics, based on [this example](https://github.com/pulumi/examples/tree/master/azure-ts-stream-analytics)
- Twitter sentiment analysis, no example yet and not sure how to integrate with Twitter without Logic Apps

Let's choose some topics, and I'll make tutorials out of them.

**Comment by joeduffy** [comment]
I've added a new `mktutorial` tool that will auto-generate tutorials from our examples repo: https://github.com/pulumi/docs/tree/master/tools/mktutorial. This feels like a better approach overall, because we can do more with less and leverage the excellent set of examples we already have over there.

The major outstanding issues are

- [ ] Tidy up the example titles/READMEs
- [ ] Reconcile duplication between existing tutorials and examples
- [ ] Figure out what to do with tutorials that don't already exist as examples
- [ ] Generate and commit all of these tutorials to the docs repo

**Comment by mikhailshilkov** [comment]
The tool is magic, looks cool! I have one uncertainty of how to proceed, though.

The readme of an example is focused on how to run that example. In other words, the code is already complete - the text just explains what it does.

A tutorial is about building something from nothing. We start with an empty template, and add components one by one, in steps.

So, how do we reconcile this difference? Do we start describing how to create each example from scratch? Only the ones we use for tutorials? Or do we put both styles side-by-side?

**Comment by joeduffy** [comment]
@mikhailshilkov This is definitely the major difference that @bermudezmt and I have been discussing what to do about. I _think_ we want the examples READMEs to be written in a more tutorial style, so that they read better in both places. It doesn't hurt to have more detail on GitHub too. But the challenge is that this is going to be a fair bit more effort and there is a lot of debt to pay down since none of the examples are written this way.

@bermudezmt What are you thinking about this these days?
