### ISSUE TITLE
Broken Helm Chart Deployment image

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1657]
File: [docs/tutorials/kubernetes/kubernetes-ts-helm-wordpress.md](https://www.pulumi.com/docs/tutorials/kubernetes/kubernetes-ts-helm-wordpress/)

**Comment by joeduffy** [comment]
If I view this in Developer Mode, I see the following error:

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://github.com/pulumi/examples/blob/master/kubernetes-ts-helm-wordpress/images/deploy.gif with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by joeduffy** [comment]
@justinvp Any idea whether we can tweak the markup to avoid CORB issues? Or should we just copy images as part of mktutorial? (Not hard, it already rewrites links.)

**Comment by justinvp** [comment]
I think the reason CORB is coming into play is because https://github.com/pulumi/examples/blob/master/kubernetes-ts-helm-wordpress/images/deploy.gif doesn't return the image itself, it returns an HTML page for viewing the image on GitHub's site. To get the actual image, I think we'd have to convert the URL to the following (which seems to work when running `make serve` locally: https://raw.githubusercontent.com/pulumi/examples/master/kubernetes-ts-helm-wordpress/images/deploy.gif

**Comment by justinvp** [comment]
Taking this since it requires some modifications to `mktutorial`.
