### ISSUE TITLE
Provide Python-specific README to pypi

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1886]
### Problem description

The main project README is being used to publish to https://pypi.org/project/pulumi/ which is showing JavaScript examples.

### Suggestions for a fix

Publish a Python-specific README for the pypi package.

**Comment by thoward** [comment]
Some considerations on this topic:

The source for content that is shown on [Pulumi's PyPi](https://pypi.org/project/pulumi/) page comes from this line of [setup.py](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/setup.py#L24) where it reads the GitHub repo's [README.md](https://github.com/pulumi/pulumi/blob/master/README.md)

That could read from another file, by adjusting the relative path, e.g. to point to the [README.md in the root of the Python SDK folder](https://github.com/pulumi/pulumi/blob/master/sdk/python/README.md). Unfortunately, that file is not up to date and needs review. 

In theory, someone could replace it, or create a new file like `README.pypi.md` which is just a copy of the GitHub repo's normal README.md, but with the TypeScript code samples converted to Python. The issue with this approach is that it requires someone *remember* to update both README files every time. They will gradually drift apart and the PyPi-specific file will become out of date.

Another possibility would be to include a Python code listing as well as a TypeScript code listing in the default README. Another idea would be to add instructions on how to use `pulumi convert` to convert the example to Python as a way of showing off Pulumi's multi-language code generation capabilities. 

That said, I think it's safe to say that since it's been 5 years since this issue was filed, and the way forward isn't really very clear (and time won't change that lack of clarity much) that this is something of a non-issue and we can safely close this ticket as `wont-fix`. Feel free to reopen if something comes up that changes any of this.
