### ISSUE TITLE
Update Jekyll configuration to not emit .html extension

### ISSUE THREAD

**Issue by lindydonna** [pulumi/docs#202]
A friend pointed out that our docs URLs look a bit "old school" with the `html` extension. There should be a simple Jekyll config that fixes this.

**Comment by lblackstone** [comment]
Here are a couple related links:
https://medium.com/@mittalyashu/how-to-remove-html-extension-in-jekyll-efeb48bd725f
https://github.com/pulumi/docs/pull/684

Summary:
Jekyll will generate links without the `.html` extension if they include a trailing `\`. A possible alternative would be creating "duplicate" S3 buckets for links with both a `link.html` key and a bare `link` key.

**Comment by chrsmith** [comment]
With #684, this should be "fixed". And it's just a matter of linking to the non-`.html` versions of files, and adding redirects to canonicalize the cleaner URLs. Let me see the extent to which we need to change things here, and if there is anything missing.

**Comment by chrsmith** [comment]
Looks like @cnunciato is a better owner for this in the current milestone. Here's my thinking about how to tackle this in the short-term:

- Move to a world where we just emit pages as `/foo/index.html` instead of `foo.html`. See https://github.com/pulumi/docs/pull/1022 and https://github.com/pulumi/docs/pull/1014 as examples of this type of approach.

An approach we _could_ take, but probably shouldn't:

- Modify `infrastructure/index.ts` to make a copy of any `.html` files it puts into S3 and removes the extension, but sets the appropriate `Content-Type` header. So we create both a `/foo.html` and `/foo` object in the S3 bucket, which would allow us to serve `/foo` and `/foo.html` when deployed.

  This actually works surprisingly well, but seems dubious because we would be fighting against Jekyll (which will always emit the .html file). It seems like if we wanted to do this, we should instead not serve content directly from S3, but standup some small web server to have the logic to map a request for `/foo` to check for an S3 object `/foo`, and if not present, fallback to `/foo.html`. (Essentially what the built-in webserver does when you run `jekyll serve`.)

**Comment by cnunciato** [comment]
Waiting on the outcome of #1034 on this (since it'd be handled by Hugo out of the box).

**Comment by justinvp** [comment]
Taking this over as I've already taken care of it as part of #1088
