### ISSUE TITLE
Document how to use Pulumi in Spinnaker

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#2197]
We get asked from time to time how to use Pulumi with Spinnaker. This work item is ultimately part of https://github.com/pulumi/docs/issues/598, however it appears sufficiently complex that a dedicated work item makes sense.

In principle, the idea here is simple: we want to execute Pulumi as part of a Spinnaker deployment pipeline, as a dedicated stage, to provision infrastructure. It's already the case that you can provision base infrastructure using Pulumi and then deploy applications to it, as discussed in [this Reddit thread about Spinnaker/Terraform](https://www.reddit.com/r/Terraform/comments/aw0dex/terraform_vs_spinnaker/eizew78/). But actually running Pulumi from Spinnaker can be useful for provisioning any of the myriad of infrastructure types that Spinnaker doesn't support out of the box.

In practice, this seems quite complex. [This video demonstrates effectively what we're trying to accomplish, just in the context of Terraform](https://www.youtube.com/watch?v=FCpsI0nYHEc). This is [documented in even more detail here](https://docs.armory.io/spinnaker/terraform_integration/). Interestingly, the stage itself has to manage cloning and interacting with the source repo; I incorrectly assumed Spinnaker would arrange to make the contents of the necessary Git repos available in advance, as a separate stage.

After installing Minnaker, [per the guide here](https://docs.armory.io/spinnaker/install/#introducing-armory-minnaker) -- by far the easiest way I found to get up and running -- the `hal armory terraform` subcommand is what drives all of this integration:

```
$ hal armory
+ kubectl -n spinnaker exec -it halyard-0 -- hal armory
ARMORY

  Armory specific commands are described here.

USAGE

  hal armory [parameters] [subcommands]

...
SUBCOMMANDS

...
  terraform
    Configure Terraform integration.
```

I've searched high and low, but can't find the source for this on GitHub. My best guess is that Armory keeps their Halyard command, and the Terraform subcommand, closed source. I've tried numerous repos -- https://github.com/armory-io/spinnaker, https://github.com/armory-io/halyard, https://github.com/spinnaker/orca, https://github.com/spinnaker/deck, etc -- and also searched Google for the phrase "Armory specific commands are described here.", but have come up empty.

It _appears_ this is a custom Spinnaker stage referred to as "terraformer" in the docs -- effectively a set of Java subclasses. That process is documented [here]( https://www.spinnaker.io/guides/developer/new-stage/). For instance, [this and surrounding classes seem to be the pipeline stages that deploy Kubernetes manifests]( https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java).

An alternative, lower effort approach, _might_ be to use a custom script stage, [as described here](https://www.spinnaker.io/reference/pipeline/stages/#script). I am guessing that has the disadvantage of needing more custom work each time it gets set up, plus not having as rich an interface back to the Spinnaker UI to display preview results, etc. Even that seems less than straightforward: it unfortunately requires setting up a Jenkins server that is configured to run the scripts.

This is looking to be a fair bit more work than our standard CI/CD system integration!

**Comment by praneetloke** [comment]
So I have spent some time looking into Spinnaker this week. Here's what I have gathered:
* Spinnaker is a CD system much like Octopus Deploy. 
* You can configure multiple cloud providers to let Spinnaker handle app deployments and also do app management (load-balancers and firewalls), again, somewhat similar to Octopus Deploy itself.
* The one added feature (over Octopus Deploy) that Spinnaker has, is the Kubernetes app deployments.
* The Kubernetes provider specifically allows users to pick a deployment rollout that fits their needs red/black, canary etc.
* Spinnaker itself does not manage the myriad of resources available with each of the major cloud providers it supports other than some basic resources. This is where I think Pulumi fits in. More specifically, I think Pulumi fits in jobs inside each Pipeline.
* Spinnaker has hooks to integrate with a Jenkins build server or with other triggers using the [standard/old artifacts](https://www.spinnaker.io/guides/user/pipeline/triggers/) UI or the [new](https://www.spinnaker.io/guides/user/pipeline/triggers-with-artifactsrewrite/) one.
* Spinnaker has _several_ micro services that handle specific things in its pipeline. See [this](https://www.spinnaker.io/reference/architecture/#spinnaker-microservices).

Some options for making Pulumi available as part of Spinnaker:

| Solution | Pros | Cons |
|---------|------|-------|
| [Pipeline Templates](https://www.spinnaker.io/guides/user/pipeline/pipeline-templates/) | Create a shareable template with a [script stage](Spinnaker uses Jenkins to sandbox your scripts) that installs the CLI, retrieves the source code, and runs it. | * Not very flexible when it comes to sharing the template. There isn't a central repository/marketplace like the [Octopus Library](https://library.octopus.com) for Pipeline Templates. <br> * Spinnaker uses Jenkins to sandbox  scripts, so that means a Jenkins server is **required** to be able to run a pipeline with a script stage. |
| [Write a New Stage](https://www.spinnaker.io/guides/developer/new-stage/) | The new stage can be submitted to the Orca repo, which means that the stage would be available natively in a following release. | * Significant development time as the stage might require both a backend (Orca) change and a frontend change.<br> * Making changes to the [frontend](https://github.com/spinnaker/deck) is not documented at all, and in fact, the repo states that they are undergoing some heavy changes to how the modules are built.<br> * Users may not be able to upgrade their Spinnaker deployment to get the new stage, which would mean they would have to manually include the new stage in their Orca micro service. (I am not sure how they would even do it.) |
| [Create a Plugin](https://www.spinnaker.io/guides/developer/plugin-creators/) | Very flexible way of extending Spinnaker with custom plugins.\n* Plugins can be installed by [users](https://www.spinnaker.io/guides/user/plugin-users/) by simply running the [halyard CLI command](https://www.spinnaker.io/guides/user/plugin-users/#adding-a-plugin) against a repo containing a plugin manifest. | * (verbatim from the docs page) Plugins are an early alpha feature that is under active development and will likely change.<br> * Plugins also require specific versions of Spinnaker deployment as well as the Halyard CLI. See [requirements](https://www.spinnaker.io/guides/user/plugin-users/#requirements). So once again, if a user cannot upgrade their Spinnaker deployment for some reason, they would not be able to use the plugin, even if we were to ignore the "early alpha" warning signs. |

So it seems that writing a plugin or a stage is probably the best way to go.

Some side notes:
* The plugin or stage will be a Java Spring framework-based application.
* Spinnaker has a component called [Kork](https://github.com/spinnaker/kork), which seems to be a common library of some sort. It might contain some useful classes that we could use in ours. But again, it is unclear what each module inside Kork is capable of. It isn't documented at all either.
* I wrote an infrastructure app that creates an AWS EC2 instance complete with automated installation of Halyard, an S3 bucket for storage. This is good for someone who doesn't need a large distributed Kubernetes-based deployment that Spinnaker recommends.
* I also have Spinnaker up/running on a [multipass](https://multipass.run/) instance for local development.

**Comment by clstokes** [comment]
I chatted with an Armory / Spinnaker person at DeliveryConf... the [Plugin creators guide](https://www.spinnaker.io/guides/developer/plugin-creators/) (in Praneet's comment - https://github.com/pulumi/docs/issues/2197#issuecomment-570010887) is their recommended new/upcoming way to build integrations. Their Terraform integration is not built using this, but only because it predates this. They'll likely be moving the TF integration to this framework at some point.

David Walker - david.walker@armory.io - is the biz dev person to reach out to in case we're interested in chatting with them.  cc @joeduffy

**Comment by danfhernandez** [comment]
This work is currently being tracked and represented in https://github.com/pulumi/home/issues/814. When that closes we can close this as well :).
