### ISSUE TITLE
aws-iam-authenticator not required for EKS

### ISSUE THREAD

**Issue by dhanvi** [pulumi/docs#2205]
### Problem description

In crosswalk eks documentation aws-iam-authenticator is mentioned as a requirement but it is no longer required by eks

Refer: https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-eks-simplifies-kubernetes-cluster-authentication/

Docs link: https://github.com/pulumi/docs/blob/master/content/docs/guides/crosswalk/aws/eks.md#prerequisites

**Comment by leezen** [comment]
Thanks for pointing out the new way to get tokens. However, we actually can't switch the documentation because of the way we generate our kubeconfig in `@pulumi/eks` (https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/cluster.ts#L153) -- so until that changes, the documentation is correct. There's a separate issue tracking switching away from aws-iam-authenticator: https://github.com/pulumi/pulumi-eks/issues/304
