### ISSUE TITLE
Link to GCP service account API documentation broken

### ISSUE THREAD

**Issue by ddgenome** [pulumi/docs#2837]
### Problem description

The link the GCP service account documentation is broken. Specifically, the link `<a href=serviceAccount/><span class="symbol module"></span>serviceAccount</a>` is broken. You'll note it is the only API item on the page with mixed case. The correct link target is `href=serviceaccount/`.

- I saw a product documentation issue on the following URL: https://www.pulumi.com/docs/reference/pkg/gcp/

### Affected product version(s)

Current version of the docs.

### Suggestions for a fix

Since these are autogenerated, I'm not sure how to fix nor understand why this one item would be broken and the rest not.

**Comment by lukehoban** [comment]
Yes - this is specific to this particular module.  We’ve fixed before in #1520 and #1314. Not sure exactly why this has crept up again in these new docs.

**Comment by justinvp** [comment]
The reason this happens is because Hugo automatically changes paths to be all lowercase. So we have two options:

1. As @Fryuni suggests, Hugo has a config setting to disable this ([`disablePathToLower`](https://gohugo.io/getting-started/configuration/), I believe), so we could set that. We'd have to do an audit of the generated site, though, to make sure there aren't any other unintended side effects.
2. Or, make a change similar to the [fix we made for the API docs](https://github.com/pulumi/docs/pull/1732), and update the resource-oriented doc gen to lowercase all URLs used for links.

**Comment by ekrengel** [comment]
Other related issue mentioned by @justinvp 
https://github.com/pulumi/pulumi/pull/4382#issuecomment-613119269
