### ISSUE TITLE
ID is missing from resource output properties

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#2975]
### Problem description

The `ID` output property is missing from most if not all resource types. This is the case across multiple providers not just AWS.

#### Specific examples:
- https://www.pulumi.com/docs/reference/pkg/gcp/compute/instance/#instance-output-properties
- https://www.pulumi.com/docs/reference/pkg/aws/ec2/vpc/#vpc-output-properties
- https://www.pulumi.com/docs/reference/pkg/aws/ec2/subnet/#subnet-output-properties
- https://www.pulumi.com/docs/reference/pkg/aws/ec2/instance/#instance-output-properties
- https://www.pulumi.com/docs/reference/pkg/digitalocean/droplet/#droplet-output-properties

#### Screenshot 

![image](https://user-images.githubusercontent.com/293763/79503186-960e9d80-7fe5-11ea-9503-e9d903975213.png)

### Suggestions for a fix

Add `ID` as an output property.

**Comment by leezen** [comment]
Related: https://github.com/pulumi/docs/issues/2884

**Comment by justinvp** [comment]
I'm guessing `id` isn't in the Pulumi schema that is generated from the TF schema, since it's [implicitly](https://github.com/pulumi/pulumi/blob/398878de31e42f7ec4485eab1c665f9aeea4c98a/sdk/nodejs/resource.ts#L656-L660) already defined on the Pulumi `CustomResource` base class.

@pgavlin, should we just be injecting an `id` in the docs for all resources? What happens if a TF resource itself defines its own `id`?

**Comment by pgavlin** [comment]
> should we just be injecting an id in the docs for all resources?

Yes.

> What happens if a TF resource itself defines its own id?

It can't: this is a reserved property in TF as well. TF datasources _should_ be injecting an ID, however, as they do include this property where we do not.

**Comment by justinvp** [comment]
I have a fix available for this. I’ll send out a PR later today/tonight. FYI, @praneetloke, @cnunciato
