### ISSUE TITLE
Do true broken link checking as part of CI

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#298]
A customer noted that https://docs.pulumi.com/reference/apis is linked from our TOC, but it should be https://docs.pulumi.com/reference/apis.html.

We've had this problem many times, because our development server allows this rewriting to work, meaning manual testing and our broken link checker don't notice any problem.  But the docs binary we use to serve the site doesn't do the same thing.

We should fix one of these systems so the two are the same and we can identify broken links correctly.

**Comment by joeduffy** [comment]
We now do this in PR, but should do post-merge validation also.

**Comment by chrsmith** [comment]
Re: commit 5378563, we need to be careful running a broken link checker against the website _as served from CloudFront_ and not just _as served from Jekyll_. As there are a few subtle differences in how the content is treated.

I don't know what Joe meant by post-merge validation, but we might want to just set up Travis to run a cron job that ran `blc` against https://staging.pulumi.io/. That would confirm that none of these "works on Jekyll but not from CloudFront" type of links slip through.

**Comment by joeduffy** [comment]
I definitely grok that they are different.

Better to validate Jekyll than nothing at all.

What I meant by "post-merge validation" was to run the checker against the website immediately after completing the deployment in that environment. I'd prefer that over a cron job, because then the failure would be attributed to the guilty commit, presumably making it easier to diagnose failures.

**Comment by chrsmith** [comment]
> then the failure would be attributed to the guilty commit, presumably making it easier to diagnose failures.

I agree with the sentiment. But I worry that we might get false negatives because the test would be served cached content. So whatever post-update test would need to either wait N minutes for the content to expire organically, or request CloudFront purge its caches explicitly. (The worse case scenario is just that the _next_, unrelated commit fails due to the broken link.)

We don't need to get too complicated here. Just things to be aware of.

**Comment by joeduffy** [comment]
I think we need to figure out how to make the update reset the CDN cache.

**Comment by chrsmith** [comment]
@justinvp this issue has evolved for a while, but with the switch to Hugo, is this no longer an issue? i.e. the behavior we get when serving localhost:1313/ is the same as when the files are served from CloudFront? If so, then we are probably good to close this issue out.

Although, it would be nice to update our `run-pulumi.sh` script for doing updates to run some `aws` CLI command to invalidate CloudFront's cache ([this comment](https://github.com/pulumi/docs/issues/298#issuecomment-417974331)).

**Comment by leezen** [comment]
Closing out this old issue. We run `blc` on a schedule now and builds are atomic, so I think this mostly covers the issues discussed here.
