### ISSUE TITLE
Functions in Go have wrong names

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#3075]
### Problem description

Functions in Go are in the form `GetThing`, but our resource docs show them in the code example as `LookupThing` which is wrong.

![image](https://user-images.githubusercontent.com/293763/80044100-5b5ea680-84b8-11ea-8531-e583eb93f28d.png)

#### Examples
- https://www.pulumi.com/docs/reference/pkg/gcp/storage/getprojectserviceaccount/#getprojectserviceaccount
- https://www.pulumi.com/docs/reference/pkg/gcp/compute/getnetwork/#using
- https://www.pulumi.com/docs/reference/pkg/aws/ec2/getvpc/#using

**Comment by praneetloke** [comment]
I think this has to do with the fact that the resource docs generator does not properly use Function name overrides for Go.

Just as an FYI, Function names are renamed and are actually sometimes renamed to use the prefix `Lookup` rather than `Get` to avoid conflicts. For example, the `GetBucket` function in the AWS package, which is actually renamed to [`LookupBucket`](https://github.com/pulumi/pulumi-aws/blob/master/sdk/go/aws/s3/getBucket.go#L14) in our  Go SDK.

**Comment by praneetloke** [comment]
The core of this issue is now fixed and the docs reflect the correct function name for Go. The thing to note here is that, in Go, the actual Function name _can_ be different from the title. It is certainly confusing and can be easy to miss. Perhaps we should add a note or something to call for the user's attention? (@cnunciato @justinvp what do you think?) The reason they can be different is because of how the function name could conflict with the resource's "get" function name. This is specific to our Go SDK.

**Comment by justinvp** [comment]
> Perhaps we should add a note or something to call for the user's attention?

I could see having a note section in that case mentioning "The function is named <inser-name> in Go."
