### ISSUE TITLE
systemDiskCategory accepted values requires correction

### ISSUE THREAD

**Issue by ankyit** [pulumi/docs#3092]
File: [docs/reference/pkg/nodejs/pulumi/alicloud/ecs/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/alicloud/ecs/)

Accepted values for the `systemDiskCategory` are `[cloud ephemeral_ssd cloud_essd cloud_efficiency cloud_ssd local_disk]`

Ref: error: alicloud:ecs/instance:Instance resource 'alicloud-web' has a problem: expected system_disk_category to be one of [all cloud ephemeral_ssd cloud_essd cloud_efficiency cloud_ssd local_disk], got cloudSsd

**Comment by lukehoban** [comment]
Apologies for a long delay!

> got cloudSsd

It looks like perhaps you passed `cloudSsd` instead of `cloud_ssd` here?  I'm going to close out, as the document list appears the same as what Ali returns in the error message.  But if you are still having problems here, please do open a new issue in the https://github.com/pulumi/pulumi-alicloud repo.
