### ISSUE TITLE
Make ensliting a new cloud provider less redundant

### ISSUE THREAD

**Issue by praneetloke** [pulumi/docs#3168]
When a new provider is added to the roster of providers Pulumi supports, adding it to our docs infrastructure means updating quite a few files. We should make that process easy somehow. Maybe just run a script that handles updating the relevant files? (Just an idea...)

**Comment by lukehoban** [comment]
We've done a decent amount of work on this since April, and it's now reasonably manageable (and in practice we add providers fairly regularly).   I expect we'll overhaul this model as part of multi-language components and eventual 3rd party package documentation publishing (i.e. gallery).  But not sure we need to track this independently as this point.
