### ISSUE TITLE
Link to language-specific API docs from resource docs 

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#3178]
Now that we've removed the links to the API docs from the API Reference page, it's become harder to find them. 

We should provide links to the language-specific docs from our module and resource pages. CDK, for example, does this with tables, with a row for each language:

Module-level: 

![image](https://user-images.githubusercontent.com/274700/80735361-6e2f3780-8ac5-11ea-8d1c-b17e778ebb63.png)

Resource-level:

![image](https://user-images.githubusercontent.com/274700/80735385-75eedc00-8ac5-11ea-8c8c-d221b7275cd4.png)

We could probably do something similar.

**Comment by praneetloke** [comment]
@sean1588  did you say that you were working on this or could I take this one?

**Comment by praneetloke** [comment]
So I have a PR ready for review for this one. One thing to note, though. I spoke to Christian about this in an offline conversation. The PR adds a table with links to the language-specific docs at the module-level on every index page, but does _not_ do that for the actual resource page. That's because the resource page already has links to the different languages in the constructor and other sections on the page. We will consider this a first iteration and see how it fares to perhaps add a table to the resource docs as well later, if needed.
