### ISSUE TITLE
Missing documentation for valid enum value bullets

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#3218]
We are missing valid values for the `mfaConfigurations` options on this resource: https://www.pulumi.com/docs/reference/pkg/aws/cognito/userpool/#inputs.

It trails off after _"Valid values:"_:

![image](https://user-images.githubusercontent.com/3953235/81120869-69fa8400-8ee2-11ea-9c98-033d753b377b.png)

The corresponding source documentation is here: https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/cognito_user_pool.markdown:

```
* `mfa_configuration` - (Optional) Multi-Factor Authentication (MFA) configuration for the User Pool. Defaults of `OFF`. Valid values:
    * `OFF` - MFA tokens are not required.
    * `ON` - MFA is required for all users to sign in. Requires at least one of `sms_configuration` or `software_token_mfa_configuration` to be configured.
    * `OPTIONAL` - MFA will be required only for individual users who have MFA enabled. Requires at least one of `sms_configuration` or `software_token_mfa_configuration` to be configured.
```

I assume we're not properly parsing the indented sub-bullets.

I wasn't sure if there was an existing item tracking this -- if so, please dupe.

**Comment by gpduck** [comment]
Is this because we're missing some "continuation phrases" to match on in this section?

https://github.com/pulumi/pulumi-terraform-bridge/blob/30d7d6a046545b1226f2e1b81f22bab4b3181b96/pkg/tfgen/docs.go#L263-L272

ex: The `create_option` property [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/managed_disk.html.markdown) would need to match on "values include" maybe?

**Comment by lukehoban** [comment]
This is fixed in current docs.
