### ISSUE TITLE
Fix scheduled builds

### ISSUE THREAD

**Issue by komalali** [pulumi/docs#3231]
### Problem description

1. The scheduled runs almost always fail on the broken link checking step. Examples: [1](https://github.com/pulumi/docs/actions/runs/97672972), [2](https://github.com/pulumi/docs/actions/runs/96675626), [3](https://github.com/pulumi/docs/actions/runs/95750022)
2. Those runs fail (amongst other things) because there are paths we are trying to exclude in `check-links.sh` which are not being successfully excluded (https://github.com/pulumi/docs/blob/master/scripts/check-links.sh#L16-L17)
3. There are also 429s returned from some of the links (github in particular), so we need to do some form of rate-limiting.

Related issue: https://github.com/pulumi/docs/issues/2978

**Comment by leezen** [comment]
Could we decouple this and have a SaaS check links for us separate from the builds?

**Comment by cnunciato** [comment]
@leezen I'm not sure I understand. Do you mean not build, but just run a job that checks the links of an existing build (such as the actual live site)?

**Comment by komalali** [comment]
I think he's referring to perhaps using a different service to check our links on the live site rather than us trying to run broken-link-checker to do so. Build vs buy, maybe because of the rate-limiting stuff? Although I do know that blc does have a rate limiting-option.

**Comment by leezen** [comment]
@cnunciato Correct, checking the actual live site (vs. build). My assumption is that scheduled builds are only being run against `master` -- in which case, it's already on the site, right?

**Comment by cnunciato** [comment]
Indeed, checking the live site makes sense to me. 

Given the work we've done so far, I'd suggest trying to make a few tweaks first to make this work, notify us, etc., before switching to a hosted service, but only because after a bit of checking, there doesn't seem to be a clear "winner" for this sort of thing as an outside service. But if you know of one that'd work, I'd be fine with giving it a try.

**Comment by leezen** [comment]
No, sadly, I don't -- I was just assuming someone's built something along those lines and it'd be easier to just pay to run it vs. trying to run this all the time ourselves. It was more a thought than a "we should definitely do this." If we feel like we can build something robust here, let's do that. 

My train of thought was along these lines:
1. Since we're checking against master in a scheduled way, we're really just checking what's on the live site.
2. If we're checking the live site, there's no reason to couple this to any kind of 'build' action (except that we have a way to run cron jobs as builds).
3. Let's not block builds on link checking (except for super critical links like `get.pulumi.com`). If this is the case, now we're open to lots of possibilities.
4. One is to continue using the build system like this as a way to kick off a checking session.
5. Another is to have a continuously running system that checks the site (which could be 'smarter' about checking heuristics like checking more recent pages more often).
4. If we're going to end up with a separate service that does this, maybe someone already built one?

I don't think we need to overthink this -- we could easily end up anywhere in the range of the last 3 options (and I'd be happy anywhere in that spectrum). Just wanted to make it clear that lots of options exist, so we should just spend the 30 minutes or whatever thinking through it and pick a path forward.
