### ISSUE TITLE
Get Resource Docs above API docs in Google search results

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#3389]
We've recently added resource docs which are *much* better primary reference material than the previous language-specific API docs.  Although we've prominently linked them from TOC, we still see the older (and less effective) docs getting the vast majority of inbound traffic.

We should strive to significantly improve the SEO of the resource docs, and to strongly discourage the language-specific API docs as primary reference material.

A few possible specific items:
- [x] Prominent links from Node.js/Python API docs back to resource docs (https://github.com/pulumi/docs/issues/2885)
- [x] Direct SEO work on the resource docs pages (H1s, etc.)
- [x] Potentially hide from search engines (or indicate as non-canonical?) on the Node.js/Python API docs pages?
- [x] Change `relref`s that point to package docs to refer to the resource docs instead (where it makes sense to do so)

**Comment by joeduffy** [comment]
@lukehoban @leezen @cnunciato I keep getting customer docs problems because a lot of folks are landing on the old API docs. As a first step towards improving this, I would strongly recommend simply adding hyperlinks to the new provider docs at the top in a very prominent way.

The other ideas are good, of course, but I'd really try to land that as quickly as we can while we figure out the more ambitious ideas that might require added design work, fwiw.

**Comment by lukehoban** [comment]
> The other ideas are good, of course, but I'd really try to land that as quickly as we can while we figure out the more ambitious ideas that might require added design work, fwiw.

Absolutely.  I've recorded the list above to be more directly in "priority order".

**Comment by cnunciato** [comment]
On this presently!
