### ISSUE TITLE
Supporting multiple examples sections in the resource docs generator

### ISSUE THREAD

**Issue by praneetloke** [pulumi/docs#3525]
### Problem description

Today we gather all examples into the the `Description` property of a resource while processing each resource in `tfgen`. With that, the resource docs generator currently only extracts the [first matched](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/examples.go#L102) `{{% examples %}}` short-code and its enclosing content for some post-processing. Instead, we should support multiple `{{% examples %}}` short-code on the same doc. That means, a doc would have multiple points on the page where a group of examples is shown. Right now, such a group is almost always at the top of the resource doc.

This [PR](https://github.com/pulumi/pulumi-terraform-bridge/pull/211) has some background comments around this, as well as this [comment](https://github.com/pulumi/pulumi-terraform-bridge/pull/211#issuecomment-640702653) specifically that shows why we might want to do this.

This would involve changes in our `tfgen` docs tool as well as the resource docs generator itself.

### Affected product version(s)

N/A

### Suggestions for a fix

Just an idea, but the `{{% examples %}}` short-code could also perhaps be enhanced with the "mount" point in the resource doc such that the examples are shown at the right point on the page rather than just the top of the page, i.e. "show this particular example for this property of this resource" etc. Right now, since the `tfgen` docs tool extracts all examples section into the `Description` property of a resource, the information about where it was originally located in the source doc is lost.

**Comment by pgavlin** [comment]
> Right now, since the tfgen docs tool extracts all examples section into the Description property of a resource, the information about where it was originally located in the source doc is lost.

This isn't quite accurate: `tfgen` only reparents H2s that are peers of the canonical `## Example Usage` section. Examples that live under other sections are left as-is.

I have to admit that I still don't see why `tfgen` et. al. need to generate `{{% examples %}}` codes. This isn't really something that is necessary for anything besides the docs site, so it seems like the schema -> docs MD translator should be responsible for inserting these if possible. The `{{% example %}}` codes are generally useful, as they provide high-level information that can be used by other targets, but I'd love to be able to emit these w/o docking them under an `{{% examples %}}` shortcode (especially b/c support for multiple `{{% examples %}}` shortcodes devolves to support for floating `{{% example %}}` shortcodes, since each of the latter could be wrapped in its own `{{% examples %}}`).
