### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by thrixton** [pulumi/docs#3672]
File: [docs/reference/pkg/aws/s3/bucketobject.md](https://www.pulumi.com/docs/reference/pkg/aws/s3/bucketobject/)

source
[pulumi.asset.Asset | pulumi.asset.Archive](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/pulumi:pulumi:Asset) => 404

**Comment by clstokes** [comment]
I just ran into this as well. This seems to be the case across all languages and we're attempting to link to the language API doc for Archives rather than our `pulumi` implementation.

e.g. 
- https://www.pulumi.com/docs/reference/pkg/aws/s3/bucketobject/#source_nodejs links to the Mozilla docs
- https://www.pulumi.com/docs/reference/pkg/aws/s3/bucketobject/#source_csharp links to Microsoft's docs

**Comment by susanev** [comment]
i do not see the links referenced in this issue, @clstokes is this still an issue?

**Comment by clstokes** [comment]
Looks like the changes to move docs into the Pulumi Registry made this a non-issue. Closing.
