### ISSUE TITLE
Consider renaming this repo from "docs" to "pulumi.io"

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#443]
Would it be a lot of work to do this? I'm not sure how disruptive it'd be to things like Travis, etc. We should discuss.

**Comment by chrsmith** [comment]
We definitely should do this. But given the apparent complications in getting Travis to play well with a renamed repo, it probably doesn't meet the bar for the current milestone.

**Comment by joeduffy** [comment]
I'm going to give it a try. Worst case, if it breaks things, I will rename it back.

**Comment by joeduffy** [comment]
On second thought, given that we have issue hyperlinks, etc., sprinkled throughout various docs and source code artifacts, I'm not sure this is worthwhile. Arguably, "pulumi.io" is not a great name for the repo anyway, since that's where the content is _published to_, whereas "docs" describes what _it is_.

**Comment by chrsmith** [comment]
I was looking into resurrecting this issue, since I still am not a fan of `pulumi/docs`. But evidently there general consensus for this sort of thing, and plenty of examples of `docs` and similarly named repos:

- `pulumi/docs`: https://github.com/chef/chef-web-docs, https://github.com/linode/docs, https://github.com/gohugoio/hugoDocs
- `pulumi/pulumi.io`: https://github.com/SparkPost/developers.sparkpost.com
- `pulumi/website`: https://github.com/kubernetes/website, https://github.com/letsencrypt/website
