### ISSUE TITLE
VPCLink docs are wrong

### ISSUE THREAD

**Issue by GaboFDC** [pulumi/docs#4498]
In the docs https://www.pulumi.com/docs/reference/pkg/aws/apigateway/vpclink/ is stated that `target_arn` should be a list of strings, and exmaples also say so.
But in reallity it dosent work like that, it allows just a simple string with the arn.

Note that the type in [here](https://www.pulumi.com/docs/reference/pkg/aws/apigateway/vpclink/#target_arn_python) correctly states is a `str` and not an array of str, but elsewhere is wrong.

**Comment by stack72** [comment]
Hi @GaboFDC 

My apologies you got hit by this bug. Technically, the docs are correct here:

```
The list of network load balancer arns in the VPC targeted by the VPC link. Currently AWS only supports 1 target.
```

The issue is, that as it's only 1 at this moment, then it is set to be a string. When AWS change to allow a list. Even the AWS CLI Docs actually say that it should be a list.

We wouldn't just change this to be a list at this moment as this would be a breaking change

I hope this helps?

Paul

**Comment by GaboFDC** [comment]
Yeah, knowing the context makes it much more clear. maybe adding a note similar to this in the meanwhile?
