### ISSUE TITLE
Consider a serif or monospace font for resource docs.

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#4558]
### Problem description

Consider a serif or monospace font for resource docs to disambiguate similar-looking characters - e.g. `amiId`.

![image](https://user-images.githubusercontent.com/293763/98735652-96db9800-2358-11eb-8473-b9555ff75663.png)

**Comment by cnunciato** [comment]
Good suggestion. Looks like the screen capture is taken from the SDK docs (https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/eks), which are slated to be removed with https://github.com/pulumi/docs/issues/4071 -- but the property names in the Resource docs (e.g., https://www.pulumi.com/docs/reference/pkg/aws/eks/cluster) also use a sans serif font (a different one, but still, not monospace). So we'll probably want to address this in the styling of definitions lists, rather than in the SDK docs, given the plans for them. 

Relatedly, we don't yet have a great heading-friendly monospace font in the stack (many of our headings, especially those with monospace words mixed into otherwise normal text, look a bit strange because of this), so this could be a good opportunity to choose a font that could work both here and elsewhere.

**Comment by susanev** [comment]
im going to close this out, we did change our fonts in the rebrand but the user experience team can revisit those when we do more significant design work in the docs.
