### ISSUE TITLE
[Recurring] Improve onboarding docs flow

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#500]
The onboarding docs aren't as smooth as they could be, and suffer from a few artifacts of where we happened to be at launch, combined with vigorous and continuous refactoring leading up to launch.

A few examples

* The flow makes it look like Pulumi only works on AWS
* We plaster the `curl` command in too many places
    - often repetitively, and
    - without sufficient context for what to do next
* The Tutorials landing page awkwardly tells you to `pulumi new`

More substantively, however, we would benefit from unifying our Install, Tutorials, and Tour pages, rather than having distinct flows for them. And it'd be great if you chose up front whether you wanted to take the tour on AWS, Azure, Google Cloud, or Kubernetes.

**Comment by lukehoban** [comment]
Per offline conversation - a suggestion was to make the following changes related to install steps:

- On pulumi.io, remove the curl line from the landing page, and rework the three buttons currently under it to have "Take A Tour", "Install" and "Examples" in that order (i.e. put "Take A Tour" before install, since the tour is perhaps the easiest way to get a taste of Pulumi.
- On https://pulumi.io/install/ change the text "Run the following command to install the latest version of Pulumi:" to something like "Run the following command to install the latest version of Pulumi or download and extract it manually" and that second part links to https://pulumi.io/install/#instructions, which is a little further down the page)
- Add yellow nag text to the end of `pulumi` invocations when there is a newer version, with a link to something like https://pulumi.io/install/upgrade.html, which explains that you just need to run that command again or download a new version and extract it.

https://github.com/pulumi/pulumi/issues/1686 is tracking the third bullet, but the other two may be worth taking into consideration as part of this work item.

**Comment by justinvp** [comment]
Close in favor of #1033 (and #997)?

**Comment by joeduffy** [comment]
@justinvp I want to keep this open as a reminder to keep making progress every sprint. I'll move out of M23, however, since we have the concrete work items filed already.
