### ISSUE TITLE
Link inside the page doesn't work https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/types/input/#KubernetesClusterNetworkProfile

### ISSUE THREAD

**Issue by diegoitaliait** [pulumi/docs#5156]
File: [docs/reference/pkg/azure/containerservice/kubernetescluster.md](https://www.pulumi.com/docs/reference/pkg/azure/containerservice/kubernetescluster/)

This links for input and out doesn't work

https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/types/input/#KubernetesClusterNetworkProfile

**Comment by stack72** [comment]
Hi @diegoitaliait 

We actually removed the python docs this week and we regenerated the resource docs to ensure those links were updated correctly

Please can you tell me if you can still find the link that 404s? 

Paul

**Comment by stack72** [comment]
My apologies @diegoitaliait, @susanev was able to point out the links that are broken

We will get that taken care of

Paul

**Comment by cnunciato** [comment]
Ah, I see -- we're matching on `types` as the service name. This should be happening only for those resources that have `Supporting Types`. I'll look into adding a redirect rule to catch it, but it'll ultimately need to be fixed by these lines in pulumi/pulumi (there are several, in `resource.tmpl` and `function.tmpl`: 

https://github.com/pulumi/pulumi/blob/95c09d88c87b7921b05e218ef42196bbcf99d13b/pkg/codegen/docs/templates/resource.tmpl#L168

**Comment by cnunciato** [comment]
Closing this issue as these links have been suppressed in the website, and for those still out there in the wild, we're redirecting properly:

```
$ curl -I https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/types/input/\#KubernetesClusterNetworkProfile
HTTP/2 301
...
location: /docs/reference/pkg/azure/?language=nodejs
cache-control: max-age=604800
```

Thanks again for the head's up @diegoitaliait! And apologies for the bumpy experience.
