### ISSUE TITLE
add docs around scim provisioning user conflicts

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#5310]
## Problem description

if users already have account when someone is scim provisioning them they will not be provisioned. lets document the situations in which this occurs, and what the person provisioning users should do to fix it. if its something the user can resolve themselves lets also document that. 

## potential fix

was mentioned that we should consider an faq section for this content

links to docs for context (contains explanation of the different scenarios): 
https://docs.google.com/document/d/16_mODtVfuGgKFM7vs9ZdMdBt8GbmXTGaArcVzFuoC8Q/edit
https://docs.google.com/document/d/18mJDn1u2c8kY7F6DHROvSEu4KS4o1EhQyeRJgeXVsPg/edit

**Comment by sean1588** [comment]
@infin8x - @praneetloke and I met to do a last walkthrough to verify some SCIM provisioning bits when it came to the user conflicts. I had noticed some unexpected behaviors in my dev environment yesterday which is why I wanted to verify. We unfortunately wrongly assumed that the email was updated when re-syncing with your third party provider, e.g. GitHub.  This was actually a pre-existing behavior in the console at an earlier point in time that was then removed at a later date,  https://github.com/pulumi/pulumi-service/pull/2929. This is also how we asked Telus to resolve the conflict issue they were having and we assumed all is well and worked for them as we had not heard anything back. This functionality was removed to get around the unique constraint we have on emails (i.e. if an email is refreshed to match the third party provider and the updated email happens to already exist in our system there would be a conflict and it wouldn't be possible) similar to what we are trying to get around from the SCIM provisioning aspect. 

Anyways, in light of this, we discussed just updating the doc for now to tell the user if there is a conflict they can optionally delete their account in order to release the email and then their organization will be able to provision the user account for them via SCIM. They can also optionally create a new pulumi account with their personal email address and transfer the stacks out to the new account if they would like to retain their existing stacks. We feel this is probably the most straight-forward process we can give them at this point in time. There are other potential workarounds, but would be a bit complicated to have the user go through them on their own without much guidance. If they would like other options we can leave a note to reach out to customer support. Then we can walk them through the process as we have been doing thus far. Given the small number of users that would likely be affected we think this is a reasonable approach for now just to get this out the door and if it ends up becoming a huge issue we can always look into prioritizing https://github.com/pulumi/pulumi-service/issues/6159. Sorry about all the confusion, let me know if this sounds reasonable and I'll update the doc with those steps.

**Comment by susanev** [comment]
im tots cool with moving forward and getting this out quickly, but i worry so much about telling users to delete their account as a solution. its really an awful experience. so if there's any way we can prioritize the follow-up work sometime soon id super advocate for that.

**Comment by praneetloke** [comment]
Thanks, Sean, for digging into this. I totally forgot that we removed updating emails via sync when we introduced the email uniqueness in the system. 😞

> but i worry so much about telling users to delete their account as a solution. its really an awful experience

Yeah agreed but if you look at the alternatives, it is not any worse unfortunately. The workarounds may involve more blocks depending on the user's specific situation. The second workaround of "connect your identity and then try reprovisioning" itself has limitations too between Okta and Azure AD. For example, in Okta you can edit failed provisioning tasks which you may need to do if, say, your GH identity used a different username than what we derive from your email in SAML/SCIM case. In Azure AD, you can't edit failed provisioning tasks. There is just no facility for that. You can edit a user profile but that's not helpful in this situation. And we don't yet know what GSuite offers. So there isn't a good solution that works across IdPs (not to mention we don't know what users will run into most of the time.)

Note that implementing https://github.com/pulumi/pulumi-service/issues/6159 may solve OAuth identity users being able to change their emails within Pulumi and unlocks the workaround of "change your email in Pulumi and then retry SCIM provisioning" (which still isn't perfect as I mentioned the case where your GH username is different from your SAML one and therefore could lead to undesirable effects.) But if the user doesn't want to do that, then the alternatives aren't good.

**Comment by infin8x** [comment]
+1, thanks for digging into this. I had a look at the latest docs - they look good to me. "contact support" is a good escape valve at our current size.

anything else to do here or should we close this?

**Comment by sean1588** [comment]
Thanks, I think we are good for now! I went ahead and just closed this out.
