### ISSUE TITLE
Getting started for Azure is not working

### ISSUE THREAD

**Issue by sujithq** [pulumi/docs#5392]
File: [docs/get-started/azure/modify-program.md](https://www.pulumi.com/docs/get-started/azure/modify-program/)

**Issue 1**
StorageAccountStaticWebsite is not available in Pulumi.AzureNative.Storage.Latest so this reference Pulumi.AzureNative.Storage should be added

``` CS
// Enable static website support
var staticWebsite = new Pulumi.AzureNative.Storage.StorageAccountStaticWebsite("staticWebsite", new 
Pulumi.AzureNative.Storage.StorageAccountStaticWebsiteArgs
{
    AccountName = storageAccount.Name,
    ResourceGroupName = resourceGroup.Name,
    IndexDocument = "index.html",
});
```

``` CS
// Upload the file
var index_html = new Pulumi.AzureNative.Storage.Blob("index.html", new Pulumi.AzureNative.Storage.BlobArgs
{
    ResourceGroupName = resourceGroup.Name,
    AccountName = storageAccount.Name,
    ContainerName = staticWebsite.ContainerName,
    Source = new FileAsset("./site/index.html"),
    ContentType = "text/html",
});
```

**Issue 2**
pulumi up throws an error:

> error reading storage account "xxx" service properties: accounts.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthenticationFailed" Message="Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:xxx\nTime:2021-03-04T10:15:28.7363385Z"

**Comment by davidwrede** [comment]
Hi @sujithq, sorry to hear you ran into issues with the new Azure getting started tutorial.

Issue #1 is because some of the project templates weren't updated yet to reflect using the top-level namespaces like `Pulumi.AzureNative.Storage`. That was fixed in https://github.com/pulumi/templates/pull/162, so if you create a new project using the `azure-csharp` the right namespaces should be set when you create a new project via the `azure-csharp` template.

For issue #2, are you using a Service Principal by chance?

**Comment by sujithq** [comment]
Hi @davidwrede,

The first issue has been resolved. Thanks.

The second issue has been resolved: there was an issue at my side. I was playing around with the current tenant in my susbscription. Doing an az login -t did the trick.

The issue can be closed.

Kind regards.

**Comment by davidwrede** [comment]
Sounds good. Glad you were able to get unblocked!
