### ISSUE TITLE
Missing docs for interfaces contained in azure.containerservice.KubernetesClusterArgs

### ISSUE THREAD

**Issue by carterwilliamson** [pulumi/docs#591]
Interfaces/objects that are contained in KubernetesClusterArgs are not defined and marked as `pulumi.Input<{}>`.
Example: 
```
KubernetesClusterArgs.networkProfile pulumi.Input<{}>
A Network Profile block as documented below.
```
There is no further documentation on the page for what fields exist in `networkProfile`

**Comment by lukehoban** [comment]
This touches on a couple of issues we are tracking:
1. We should display the actual types instead of `...` in the docs: part of https://github.com/pulumi/docs/issues/492.
2. Inner structs should be given names and presented as first class things in the docs and API (including attaching documentation of the inner fields): https://github.com/pulumi/pulumi-terraform/issues/163

The best resource we have currently for this is the `.d.ts` files.  These are actually linked from the headers in the docs - like `property agentPoolProfile` which links to https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/containerservice/kubernetesCluster.ts#L245.

Addressing the two issues above, plus improving the raw documentation text itself, will be key to improving on this.

**Comment by carterwilliamson** [comment]
Thanks for the update @lukehoban if you feel this is covered by other issues, then this can be closed. 👍
