### ISSUE TITLE
Links on Kubernetes-Nodejs documentation are broken

### ISSUE THREAD

**Issue by Korede-TA** [pulumi/docs#599]
It appears that the renamed directory [`sdk`](https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk) -> [`pack`](https://github.com/pulumi/pulumi-kubernetes/blob/master/pack) on [pulumi/pulumi-kubernetes](https://github.com/pulumi/pulumi-kubernetes) is causing links on the [kubernetes-nodejs docs](https://pulumi.io/reference/pkg/nodejs/@pulumi/kubernetes) site to break.

For example, this link does not work: https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/types/output.ts
But this one does: https://github.com/pulumi/pulumi-kubernetes/blob/master/pack/nodejs/types/output.ts

Please fix.

**Comment by joeduffy** [comment]
We'll get this fixed.

I think the issue here is that our doc generator assumes everything is in a directory named `sdk/` (it is for AWS, Azure, Google Cloud, etc). But the Kubernetes repo stores it in `pack/`.

A simple fix is to just change the Kubernetes repo structure to match the others. @hausdorff , any objections?

**Comment by lukehoban** [comment]
This was fixed with https://github.com/pulumi/pulumi-kubernetes/pull/227.
