### ISSUE TITLE
Firestore Index docs page is unavailable

### ISSUE THREAD

**Issue by xSAVIKx** [pulumi/docs#6206]
## Steps to reproduce

1. Go to https://www.pulumi.com/docs/reference/pkg/gcp/firestore/index page.
2. See 404 instead of the docs.

![image](https://user-images.githubusercontent.com/5675689/124366879-ac8d2d00-dc5b-11eb-8d95-2380095b54ef.png)

Expected: We can see and use the docs page.
Actual: We see the 404 stub.

**Comment by cnunciato** [comment]
@xSAVIKx Thanks for reporting this. It also seems to be happening with `google-native/datastore` and `google-native/firestore` for the same reason, namely that the resources themselves are called `index`, which is a kind of reserved word for Hugo in this context.

To fix it, we'll need to change the way we name our generated Markdown files (e.g., to use `resource-name/_index.md` instead of `resource-name.md`), but we should be able to get it looked at soon.

**Comment by cnunciato** [comment]
This should be fixed-fixed with the next update of the GCP provider docs. (I'll see if I can kick off one now.)

**Comment by cnunciato** [comment]
@xSAVIKx Here you go! Thanks again for the report.

https://www.pulumi.com/docs/reference/pkg/gcp/firestore/index/
