### ISSUE TITLE
Add Python API docs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#630]

**Comment by swgillespie** [comment]
Here's my plan for this:

1. Fix https://github.com/pulumi/pulumi-terraform/issues/168. Doing this will make it monumentally easier to generate high-quality documentation.
2. Python makes it extremely easy to inspect modules and programmatically extract documentation from them. This is what pydoc does. Pydoc is very opinionated about its output HTML format so we should do what Boto has done here and write a script that extracts documentation from our packages and formats it as documentation.
3. With our documentation tool in-hand, we can then begin annotating fields of type `TypeMap` in Terraform with the exact dictionary state that TF is expecting, so that we can generate documentation for them. Python has no explicit syntax for this but, if we own the documentation generator, we can use normal Python metaprogramming techniques to accomplish this.

The end result is high-quality generated documentation from Python modules. This involves writing a pydoc-like Python script for inspected our own modules. Luckily Python has extremely robust standard library support for doing this ([`inspect`](https://docs.python.org/3/library/inspect.html) and [`importlib`](https://docs.python.org/3/library/importlib.html)`). The big downside here is that writing a program like this is advanced Python that can get confusing.

For M20, I plan on taking steps 1 and 2. Step 3 is absolutely required for good documentation but it's out of scope for M20 since it's a bit more work.

**Comment by swgillespie** [comment]
To elaborate on 2, Boto accomplishes this by reflecting over the services that it provides and generates files that are ultimately fed to Sphinx, which generates HTML.

This may or may not be a good idea for us to adopt - I'm not sure yet. We've had a lot of success using tsdoc to generate json which we can then use to produce documentation that is still within the style and scheme of our existing documentation. Sphinx is opinionated and wants to control its output format. It may be hard to get Sphinx to play well with our existing documentation theme.

That said, Sphinx is the "standard" tool in this space and it would be nice just for practical reasons to stick as close to the "standard" path as possible.

**Comment by swgillespie** [comment]
The first bits of API documentation have been merged into this repo. I will be creating follow-up issues for concrete M21 tasks to keep improving on what we have.
