### ISSUE TITLE
update hugo modules refernces to master regularly failes on cypress tests

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#8245]
this has happened at least 4 times in the last few days
someone should look into this

here is an example: https://github.com/pulumi/docs/actions/runs/3488511386/attempts/1

pls let me know how i can help

**Comment by susanev** [comment]
Failed again today
https://github.com/pulumi/docs/actions/runs/3570924091/jobs/6002342241

**Comment by sean1588** [comment]
I did a bit of digging on this today, and think it is likely due to the website files not being fully ready to serve once the cypress tests start running. The [last occurrence ](https://github.com/pulumi/docs/actions/runs/3883210190/jobs/6624252543)of this error was about 2 weeks ago so we removed the P1 label. We [run the tests right after the content is uploaded](https://github.com/pulumi/docs/blob/master/scripts/sync-and-test-bucket.sh#L71), so I am guessing these anomalies are due to aws being slow sometimes and the content is not yet available once we start running the tests.  I was not able to repro this issue locally, which kinda makes sense if my above theory is correct. I can add some retry logic to the script to try and run the test again if we end up catching a failure.
