### ISSUE TITLE
Examples code in `pulumi/pulumi` doc comments getting dropped

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#884]
The code example in the doc comments here: 

https://github.com/pulumi/pulumi/blob/6f386567f6a8494853bee8fccdb455b3be1a993b/sdk/nodejs/output.ts#L70

Is not present here:

https://pulumi.io/reference/pkg/nodejs/@pulumi/pulumi/#Output-apply

It appears our doc generation is stripping out the code example

**Comment by justinvp** [comment]
The issue seems to stem from the fact that the language is specified as `ts` instead of `typescript`. Haven't gotten into the details yet, but for some reason when `ts` is used, the HTML is emitted, but it has `display: none` on the element, which hides it.

**Comment by justinvp** [comment]
The problem is with our `langchoose.js`. It sees tabs at the top of the page for JavaScript and TypeScript, and goes through and hides all code snippets that aren't the selected language (and JavaScript is selected by default). All our doc comment examples are in TypeScript, so they're all hidden by default.

Even if you select TypeScript, the snippets remain hidden because the doc comment examples use `ts` as the language and the `langchoose.js` is only looking for `typescript`. We could go fix those examples in pulumi/pulumi be `typescript` but a more general fix would be to make `langchoose.js` recognize that `ts` is the same as `typescript`.
