### ISSUE TITLE
poor search experiences

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#9109]
Here’s a quick summary from back when I was looking at the crosswalk docs…
Searching from within the registry
“AWS” results:

- :white_check_mark: AWS Package from registry
- :white_check_mark: AWS-native package from registry
- :question: AWS-IAM package from registry (not actively supported)

“Awsx” results:

- Only show awsx in registry, not crosswalk
- No crosswalk guide link

:x: “Crosswalk” results only show “Crosswalk for Kubernetes” package (unmaintained) - no AWSx or EKS or guide

- Search from within the docs

“AWS” returns same results as above

- “Awsx”
- Awsx package
    - Pulumi crosswalk for aws guide
    - Blog post
    - [Typescript-only SDK docs](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/) (this should probably not exist any more)
- “Crosswalk”
    - “Crosswalk for AWS” guide
    - “Crosswalk for Kubernetes” guide
    - “Crosswalk for Kubernetes” package
    - Blog posts
    - :x: No link to AWSx or EKS in the registry

**Comment by cnunciato** [comment]
I've read this issue a few times now, and I'm afraid I don't quite understand all that it's saying. 

@danielrbradley if you have a few, would you mind fleshing out what you were expecting vs. what you saw here so I can be sure what we're building addresses everything properly?

**Comment by danielrbradley** [comment]
@cnunciato here's the original doc where this was taken from which might give better context:

https://docs.google.com/document/d/1dRR7zJoP_EM-nSsnVK9LfdJStCW_q_GNWV2veLvGKhI

**Comment by cnunciato** [comment]
>"AWS” results:
>  ✅ AWS Package from registry
>  ✅ AWS-native package from registry
> ❓ AWS-IAM package from registry (not actively supported)

All right I think we're good here -- queries for `aws` surface the AWS tutorials and guides (in Docs) and AWS Classic and Native (in Registry), in that order. 

> “Awsx” results:
>  Only show awsx in registry, not crosswalk
>  No crosswalk guide link

I'm assuming this means it's a bug that "awsx" doesn't yield the AWS Guides. This is still happening because there's a lot of content containing "awsx" in the title/H1 tags, which rank highly in search, so the content we want to promote (which is lacking these terms in the titles) is getting outranked.

As a temporary measure, we can manually promote these pages in results (PR in the works now), but we'll probably want to consider putting "Crosswalk" and/or "AWSx" in the titles or H1 tags to better align our content with queries.
