### ISSUE TITLE
something is up with how we cache css

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#9198]
it seems our css cacheing is maybe not working
as folks who leave docs pages open for a few days
return to a css-less docs page

this may have always been an issue
but since we rarely made css change in the past we may have not known about it

we should investigate this and fix it
as it is a poor user experience

**Comment by cnunciato** [comment]
Let's take a look at how we bundle and deliver our files and how the CloudFront cache is configured for them. If we're unable to repro this issue (e.g., on a dev stack) and everything looks correct, let's close.

**Comment by susanev** [comment]
both myself and @komalali could repro this consistently. you should be able to repro it yourself if you leave a docs tab open before a css change lands, and then go to that tab again after the css change lands.

**Comment by cnunciato** [comment]
We just had a deployment that modified the CSS bundle (and thus changed the filename):

Before the deployment:

<img width="500" alt="image" src="https://github.com/pulumi/docs/assets/274700/03f5def0-6d28-4e49-b213-31522c3ae7fd">

After the deployment, having navigated to another page in the same tab (in Chrome, with the dev tools closed at time of navigation):

<img width="500" alt="image" src="https://github.com/pulumi/docs/assets/274700/2ea4433f-6269-4f5a-a4ab-80860b85cefe">

So it looks like this no longer repros -- at least as described.

I hesitate slightly to close, because the [last time this issue was mentioned](https://pulumi.slack.com/archives/C85BS3LJZ/p1685376193303669) was after the [latest change to the caching rules](https://github.com/pulumi/docs/pull/9115) (which had been set to five minutes; they're now set to one year) -- but given that change, and that it's been a couple of months since it's been mentioned (Community Slack is clear as well), and that we have no repro, and the current caching rules seem right, I'm comfortable closing for now. 

Definitely feel free to reopen with a repro, though, if you witness it again.
