### ISSUE TITLE
Add Linting / Spellcheck to Pipelines

### ISSUE THREAD

**Issue by ekrengel** [pulumi/docs#956]
We should add markdown linting and spellchecker to our pipeline to force consistency + correct spelling.

For markdown linting -- this would be things $ should only be present when the code snippet also includes output.

**Comment by susanev** [comment]
@cnunciato should we close this? move it to pulumi-hugo? something else?

**Comment by thoward** [comment]
This is a good idea, but I imagine there are some significant barriers to consider. We are currently working on grooming the documentation repo backlog and since we haven't had any motion on this in three years, and half of the ticket is completed, I'm going to close this ticket. If you think it should be re-opened, please leave a comment here and we can revisit it.
