### ISSUE TITLE
pulumi destroy fails using quickstart/aws/tutorial-eks.md

### ISSUE THREAD

**Issue by cwiggs** [pulumi/docs#991]
It looks like when following the eks tutorial `pulumi destroy` fails.  The error is:

```
  aws:ec2:SecurityGroup (helloworld-nodeSecurityGroup):
    error: Plan apply failed: deleting urn:pulumi:lab::eks-hello-world::eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::helloworld-nodeSecurityGroup: DependencyViolation: resource sg-05fe8ed2e73
8292aa has a dependent object
        status code: 400, request id: aff8108b-5d0d-4a89-90ea-31582c908f39
```

I believe the issue is that the security group has security group rules and the api call to delete is not sending the "force delete even if sg rules are attached".  The aws-infra package is what is creating the VPC and the security groups, but I'm not 100% sure where to find the code for aws-infra, or even if it should be updated as it looks like the awsx package might have replaced it?

**Comment by cwiggs** [comment]
It looks like the issue isn't the security group rules like I originally thought.  Instead there is an EIN attached to the SG which causes the SG deletion to fail.  I confirmed this by trying to delete the SG manually via the AWS console.

**Comment by eyesmoker** [comment]
is there a workaround for this until we the right solution? We are having the same issue and this is becoming blocker.

**Comment by cwiggs** [comment]
@eyesmoker If you detach the SG from the EIN and run `pulumi destroy` it should destroy successfully.

**Comment by metral** [comment]
This is long standing [issue](https://github.com/aws/amazon-vpc-cni-k8s/issues/69) with the `aws-k8s-cni` plugin where the ENIs are not properly cleaned up on tear downs due to either a) lingering ENIs from a LB service that wasn't deleted or b) the plugin itself was terminated before its clean up finished.

As @cwiggs mentions, you can manually detach the ENI from the SG, and then you should be able to destroy as expected.

**Comment by lukehoban** [comment]
The upstream CNI issue has been resolved and this should no longer be a problem.
