### ISSUE TITLE
google_beta referenced but undefined

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#9932]
### Problem description

From a [community member](https://pulumi-community.slack.com/archives/CRFUR2DGB/p1694973589413989):

`google_beta` is referenced in several samples, but doesn’t appear to be defined any where. Example:
```
const privateNetwork = new gcp.compute.Network("privateNetwork", {}, {
    provider: google_beta,
});
```

### Affected :

https://www.pulumi.com/registry/packages/gcp/api-docs/sql/databaseinstance/

Furthermore, it looks like there are hundreds of pages with this problem: https://www.google.com/search?q=site%3Apulumi.com+%22google_beta%22

**Comment by cnunciato** [comment]
After [checking with a few team members](https://pulumi.slack.com/archives/C011EMDQ8JE/p1696018577773059), it looks like the root of this issue is pulumi/pulumi#12354, so I'll close this for now as a duplicate, as a fix for that issue would correct this one as well (and others that fall into this category).
