### ISSUE TITLE
Pulumi CLI documentation lacks information on pulumi ai

### ISSUE THREAD

**Issue by scottslowe** [pulumi/docs#9972]
### Problem description

A community user pointed out that the Pulumi CLI documentation (https://www.pulumi.com/docs/cli/) lacks any documentation on the `pulumi ai` command (the user specifically referenced `pulumi ai web`).

### Affected product version(s)

This should only affect the CLI versions that include `pulumi ai` commands.

### Suggestions for a fix

We just need to add `pulumi ai` to the CLI page with appropriate explanation/details.

**Comment by thoward** [comment]
Note: This is due to the `make generate` command, which runs `pulumi gen-markdown <path>`, but does not set the `PULUMI_EXPERIMENTAL=true` environment variable, which means that the experimental `ai` subcommand is hidden during the run, and Cobra doesn't generate the file for those commands. Enabling that flag generates the appropriate files.
